name: rust

on: [push, pull_request]

jobs:
  build:
    name: Rust ${{ matrix.rust-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust-version: [1.45.0, beta, nightly]
        include:
        - rust-version: nightly
          continue-on-error: true

    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust-version }}
    - uses: actions/checkout@v1
    - name: Check formatting
      if: matrix.rust-version != 'nightly'
      run: |
        rustup component add rustfmt
        cargo fmt --all -- --check
    - name: Build
      continue-on-error: ${{ matrix.continue-on-error }}
      run: cargo build --all --verbose
    - name: Run tests
      continue-on-error: ${{ matrix.continue-on-error }}
      run: cargo test --all --verbose
